services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3309:3306"
    volumes:
      - ./demo:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s

  sql-mcp:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SQL_MCP_DB_TYPE: mysql
      SQL_MCP_DB_HOST: mysql
      SQL_MCP_DB_PORT: 3306
      SQL_MCP_DB_USER: root
      SQL_MCP_DB_PASSWORD: root
      SQL_MCP_DB_NAME: mydb
      SQL_MCP_DB_TIMEOUT: 20000
      SQL_MCP_MCP_TRANSPORT: http
      SQL_MCP_MCP_HTTP_PORT: 3000
    ports:
      - "3001:3000"
    command: ["--transport", "http", "--httpPort", "3000"] 